### ISSUE TITLE
map does not seem to work

### ISSUE THREAD

**Issue by 030** [030/go-yq#54]
`go-yq '.a.b'` does not match

```
a:
- b:
  - c: 123
    d: 456
    e:
      f: 789
  aa:
  - bb: 111
    cc: 222
    dd: 333
```
